import mongoose from "mongoose";

const articleSchema = new mongoose.Schema(
  {
    entreprise: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Entreprise",
      required: true,
    },
    codeArticle: { type: String, required: true },
    designation: { type: String, default: "" },
    designation2: { type: String, default: "" },
    gencode: { type: String, default: "" },
    reference: { type: String, default: "" },
    codeFourn: { type: Number, default: 0 },
    fournisseur: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Fournisseur",
      default: null,
    },
    prixRevient: { type: Number, default: 0 },
    prixVenteHT: { type: Number, default: 0 },
    prixDetail: { type: Number, default: 0 },
    prixAchat: { type: Number, default: 0 },
    prixPromo: { type: Number, default: 0 },
    prixVenteTTC: { type: Number, default: 0 },
    dernierPrixRevient: { type: Number, default: 0 },
    qt2: { type: Number, default: 0 },
    pr2: { type: Number, default: 0 },
    qt3: { type: Number, default: 0 },
    pr3: { type: Number, default: 0 },
    stockMini: { type: Number, default: 0 },
    stock: { type: Number, default: 0 },
    stockLocal2: { type: Number, default: 0 },
    reserve: { type: Number, default: 0 },
    stockSecurite: { type: Number, default: 0 },
    s1: { type: Number, default: 0 },
    s2: { type: Number, default: 0 },
    s3: { type: Number, default: 0 },
    s4: { type: Number, default: 0 },
    s5: { type: Number, default: 0 },
    unite: { type: String, default: "" },
    conditionnement: { type: Number, default: 0 },
    enCoursCommande: { type: Number, default: 0 },
    groupe: { type: String, default: "" },
    taxes: { type: Number, default: 0 },
    tva: { type: Number, default: 0 },
    txADeduire: { type: Number, default: 0 },
    observation: { type: String, default: "" },
    pourcentage: { type: Number, default: 0 },
    ventes: {
      v1: { type: Number, default: 0 },
      v2: { type: Number, default: 0 },
      v3: { type: Number, default: 0 },
      v4: { type: Number, default: 0 },
      v5: { type: Number, default: 0 },
      v6: { type: Number, default: 0 },
      v7: { type: Number, default: 0 },
      v8: { type: Number, default: 0 },
      v9: { type: Number, default: 0 },
      v10: { type: Number, default: 0 },
      v11: { type: Number, default: 0 },
      v12: { type: Number, default: 0 },
    },
    ruptures: {
      r1: { type: Number, default: 0 },
      r2: { type: Number, default: 0 },
      r3: { type: Number, default: 0 },
      r4: { type: Number, default: 0 },
      r5: { type: Number, default: 0 },
      r6: { type: Number, default: 0 },
      r7: { type: Number, default: 0 },
      r8: { type: Number, default: 0 },
      r9: { type: Number, default: 0 },
      r10: { type: Number, default: 0 },
      r11: { type: Number, default: 0 },
      r12: { type: Number, default: 0 },
    },
    douane: { type: String, default: "" },
    devise: { type: String, default: "" },
    dateInventaire: { type: Date, default: null },
    dateInventaire2: { type: Date, default: null },
    dateCreation: { type: Date, default: null },
    datePromoDebut: { type: Date, default: null },
    datePromoFin: { type: Date, default: null },
    depreciation: { type: Number, default: 0 },
    codeMaj: { type: String, default: "" },
    codeTarif: { type: String, default: "" },
    codeTGC: { type: String, default: "" },
    gism1: { type: String, default: "" },
    gism2: { type: String, default: "" },
    gism3: { type: String, default: "" },
    gism4: { type: String, default: "" },
    gism5: { type: String, default: "" },
    place: { type: String, default: "" },
    tarifLibre: { type: Boolean, default: false },
    texte: { type: String, default: "" },
    gencodeDouble: { type: String, default: "" },
    associe: { type: String, default: "" },
    photo: { type: String, default: "" },
    web: { type: String, default: "" },
    designationFournisseur: { type: String, default: "" },
    couleur: { type: String, default: "" },
    commandeSpeciale: { type: Number, default: 0 },
    renvoi: { type: String, default: "" },
    compose: { type: String, default: "" },
    volume: { type: Number, default: 0 },
    kl: { type: String, default: "" },
    sav: { type: String, default: "" },
    garantie: { type: String, default: "" },
  },
  {
    timestamps: true,
  }
);

articleSchema.index({ entreprise: 1, codeArticle: 1 }, { unique: true });
articleSchema.index({ entreprise: 1, codeFourn: 1 });
articleSchema.index({ entreprise: 1, gencode: 1 });
articleSchema.index({ entreprise: 1, fournisseur: 1 });

const Article = mongoose.model("Article", articleSchema);

export default Article;